### ISSUE TITLE
[SOB] BDK Wallet Infrastructure

### ISSUE THREAD

**Issue by rajarshimaitra** [citadel-tech/coinswap#122]
# BDK Wallet Infrastructure

## Description

The current Coinswap wallet is an ad hoc demo wallet that is highly inefficient and insecure. The majority of the wallet code resides in the `src/wallet/api.rs` module, with other wallet APIs distributed in corresponding modules in `src/wallet`.

This project aims to utilize the BDK library to redesign the wallet infrastructure. All existing top-level APIs of the current wallet should remain functional. Utilize the latest BDK release and the internal structures defined in the BDK chain module to construct the wallet interface. Refer to the BDK Wallet as a guide on how to employ the BDK chain interfaces to construct any custom wallet.

The revamped BDK wallet should be capable of synchronizing with Bitcoin Core RPC.

## Expected Outcomes

- Creation of a new `Wallet` struct utilizing BDK chain interfaces.
- Preservation of functionality for all current top-level Wallet APIs.
- Ability of the new Wallet to synchronize with Bitcoin Core RPC.

## Resources

- [Current Coinswap Wallet APIs](https://github.com/utxo-teleport/teleport-transactions/blob/master/src/wallet/api.rs)
- [BDK chain interfaces](https://github.com/bitcoindevkit/bdk/blob/master/crates/chain/src/indexed_tx_graph.rs)
- [BDK Wallet APIs](https://github.com/bitcoindevkit/bdk/blob/master/crates/bdk/src/wallet/mod.rs)
- [BDK RPC Blocks emitter](https://github.com/bitcoindevkit/bdk/blob/master/crates/bitcoind_rpc/src/lib.rs)

## Skills Required

- Proficiency with Git. [Guide](https://git-scm.com/book/en/v2)
- Experience with Rust. [First seven chapters of the book](https://doc.rust-lang.org/book/)
- Ability to set up a local core node in regtest mode and mine blocks.
- Familiarity with BDK v1.0 API.
- Familiarity with Coinswap Wallet.

## Mentor(s)

@rajarshimaitra @Shourya742

## Difficulty

Hard

## Competency Test

- Install Rust, compile, and run all the Coinswap tests.
- Set up a local Bitcoin Core in regtest mode. Create a wallet, receive and send transactions via bitcoin-cli.
- Run and familiarize yourself with the [example_bitcoind_rpc_polling](https://github.com/bitcoindevkit/bdk/tree/master/example-crates/example_bitcoind_rpc_polling).

**Comment by 15IITian** [comment]
## Approach for working on it > 

### Task List: 
- [ ] Segregate whole wallet related files into two `BDK_Wallet` & `SwapCoin` where:
  - `BDK_wallet` directory contains files which are general purpose
  - `SwapCoin` one contains specific files as the name suggests
  - [ ] Currently, all general-purpose and SwapCoin specific APIs are mixed up in various files like in `Wallet/api.rs` -> Thus there's a need to segregate them.

- [ ] Modify `WalletStore` struct and implement certain more traits:
  - [ ] Remove `master_key` field from struct -> can raise security issues
  - [ ]  move `wallet_file_path` field here from `Wallet` ( as it is more related to backend portion)
  - [ ] Implement `PersistentBackend` trait:
     -  This would allow changes to be staged and finalized selectively on further considerations which will enhance data integrity.

 - [ ] Add `Fidelity`, `SwapCoin` variants to `KeychainKind` enum where:
    -   `Fidelity` = 2  ( `FIDELITY_DERIVATION_PATH: &str = m/84'/0'/0'/2`)
    -  `SwapCoin` = 3
- [ ] Use the `KeyChainTxOutIndex` struct from BDK 
   -  apply logic to support swapcoin  keychainkind
   

- [ ]  Modify `Wallet` Struct:
   - [ ]  remove `rpc` & `store` field 
   - [ ]  move `wallet_file_path` field from this struct to `WalletStore` ( as it is more related to backend portion)
   - [ ]  Add all fields same as BDK wallet one with some tweaks:
      - [ ]  Use HashMap to relate each `Arc<SignersContainer>` to its corresponding `KeychainKind` instead of having seperate field for each keychainkind as done in BDK wallet  as ( `signers= HashMap<KeychainKind, Arc<SignersContainer>>` )
      
- [ ] Remove  `DisplayAddressType` struct and its impl:
   -  It is not used anywhere 
      
 - [ ]  Reconstruct `init` wallet function :
     -  coinswap  wallet will act as like  regular one  -> will  take only `internal` & `external` discriptors

- [ ]  create our own `signers` related api's ( BDK signers api's are only meant for `internal` & 'external` keychain)
   - [ ] build `create_signers` fn
   - [ ] build  `add_signers`  which will add an external signer to a particular keychain

- [ ]  Rebuild `load` wallet function ( use `BDK load` wallet api logic)
- [ ]  modify `create_and_import_coinswap_address` api 
- [ ]  Synchronizing modified wallet with Bitcoin Core RPC:
   -  use logic of `Sync variant` command of `RpcCommands` enum  in  `example_bitcoind_rpc_polling` example given in BDK

**Comment by 15IITian** [comment]
### Approach for working on it-> 

#### Task List: 
- [ ] Segregate whole wallet related files into two `BDK_Wallet` & `SwapCoin` where:
  - `BDK_wallet` directory contains files which are general purpose
  - `SwapCoin` one contains specific files as the name suggests
  - [ ] Currently, all general-purpose and SwapCoin specific APIs are mixed up in various files like in `Wallet/api.rs` -> Thus there's a need to segregate them.

- [ ] Modify `WalletStore` struct and implement certain more traits:
  - [ ] Remove `master_key` field from struct -> can raise security issues
  - [ ]  move `wallet_file_path` field here from `Wallet` ( as it is more related to backend portion)
  - [ ] Implement `PersistentBackend` trait:
     -  This would allow changes to be staged and finalized selectively on further considerations which will enhance data integrity.

 - [ ] Add `Fidelity`, `SwapCoin` variants to `KeychainKind` enum where:
    -   `Fidelity` = 2  ( `FIDELITY_DERIVATION_PATH: &str = m/84'/0'/0'/2`)
    -  `SwapCoin` = 3
- [ ] Use the `KeyChainTxOutIndex` struct from BDK 
   -  apply logic to support swapcoin  keychainkind
   

- [ ]  Modify `Wallet` Struct:
   - [ ]  remove `rpc` & `store` field 
   - [ ]  move `wallet_file_path` field from this struct to `WalletStore` ( as it is more related to backend portion)
   - [ ]  Add all fields same as BDK wallet one with some tweaks:
      - [ ]  Use HashMap to relate each `Arc<SignersContainer>` to its corresponding `KeychainKind` instead of having seperate field for each keychainkind as done in BDK wallet  as ( `signers= HashMap<KeychainKind, Arc<SignersContainer>>` )
      
- [ ] Remove  `DisplayAddressType` struct and its impl:
   -  It is not used anywhere 
      
 - [ ]  Reconstruct `init` wallet function :
     -  coinswap  wallet will act as like  regular one  -> will  take only `internal` & `external` discriptors

- [ ]  create our own `signers` related api's ( BDK signers api's are only meant for `internal` & 'external` keychain)
   - [ ] build `create_signers` fn
   - [ ] build  `add_signers`  which will add an external signer to a particular keychain

- [ ]  Rebuild `load` wallet function ( use `BDK load` wallet api logic)
- [ ]  modify `create_and_import_coinswap_address` api 
- [ ]  Synchronizing modified wallet with Bitcoin Core RPC:
   -  use logic of `Sync variant` command of `RpcCommands` enum  in  `example_bitcoind_rpc_polling` example given in BDK

**Comment by 15IITian** [comment]
## Points about `CoinSwap` wallet: 
   - This wallet has all the general-purpose features of regular wallets like BDK wallets, but it is also compatible with the `CoinSwap` protocol.
  
   - Upon initializing the wallet, we can't judge if it will be used for CoinSwap ; it can also function as a regular wallet. However, the main objective of creating this wallet is to support `CoinSwap` in addition to regular features.

**Comment by 15IITian** [comment]
For now, I haven't considered the idea of not using a descriptor for Coinswap, as discussed in the previous dev sync. I believe it needs more discussion.
