### ISSUE TITLE
`SoB/BDKWallet`: `BDK Wallet Infrastructure` project approach.

### ISSUE THREAD

**Issue by 15IITian** [citadel-tech/coinswap#142]
Here is the approach for working on this project idea #122 -> 

# Task List: 
- [x] #157
   -  It is not used anywhere 
      
- [x] #156
   - create `bdk.rs` module containing all wallet module code for working on `BDK project`.

- [x] #155
   -   `Fidelity` = 2  ( `FIDELITY_DERIVATION_PATH: &str = m/84'/0'/0'/2`)
   -  `SwapCoin` = 3
- [x] #154
  - [ ] Remove `master_key` field from struct -> can raise security issues
  - [ ]  move `wallet_file_path` field here from `Wallet` ( as it is more related to backend portion)
  - [ ] Implement `PersistentBackend` trait:
     -  This would allow changes to be staged and finalized selectively on further considerations which will enhance data integrity.

- [ ] Use the `KeyChainTxOutIndex` struct from BDK 
   -  apply logic to support swapcoin  keychainkind
   

- [x] #163
   - [ ]  remove `rpc` & `store` field 
   - [ ]  move `wallet_file_path` field from this struct to `WalletStore` ( as it is more related to backend portion)
   - [ ]  Add all fields same as BDK wallet one with some tweaks:
      - [ ]  Use HashMap to relate each `Arc<SignersContainer>` to its corresponding `KeychainKind` instead of having seperate field for each keychainkind as done in BDK wallet  as ( `signers= HashMap<KeychainKind, Arc<SignersContainer>>` )
      
 - [x] #179
     -  coinswap  wallet will act as like  regular one  -> will  take only `internal` & `external` discriptors

- [x] #173
   - [ ]   build  `create_signers` fn
   - [ ] build  `add_signers`  which will add an external signer to a particular keychain

- [x] #180
- [ ]  modify `create_and_import_coinswap_address` api 
- [x] #201
   -  use logic of `Sync variant` command of `RpcCommands` enum  in  `example_bitcoind_rpc_polling` example given in BDK 

- [x] #203

**Comment by 15IITian** [comment]
## Points about `CoinSwap` wallet: 
   - This wallet has all the general-purpose features of regular wallets like BDK wallets, but it is also compatible with the `CoinSwap` protocol.
  
   - Upon initializing the wallet, we can't judge if it will be used for CoinSwap ; it can also function as a regular wallet. However, the main objective of creating this wallet is to support `CoinSwap` in addition to regular features.

**Comment by 15IITian** [comment]
For now, I haven't considered the idea of not using a descriptor for Coinswap, as discussed in the previous dev sync. I believe it needs more discussion.

**Comment by 15IITian** [comment]
#122 is more better to have these content .

**Comment by mojoX911** [comment]
new tracking will be created..
